/**
 * colors.h
 * --------
 * Provides cool and vibrant colors for the game. Notably: black and white.
 */
#ifndef PROJET_PASTEQUE_COLORS_H
#define PROJET_PASTEQUE_COLORS_H

#include "libGameRGR2.h"

typedef int ColorId;

// Basic colors
#define PASTEQUE_EXT_COLOR(n) (16+n)
#define PASTEQUE_COLOR_TOMATO PASTEQUE_EXT_COLOR(1)
#define PASTEQUE_COLOR_FUSCHIA PASTEQUE_EXT_COLOR(2)
#define PASTEQUE_COLOR_TURQUOISE PASTEQUE_EXT_COLOR(3)
#define PASTEQUE_COLOR_GREEN PASTEQUE_EXT_COLOR(4)
#define PASTEQUE_COLOR_ORANGE PASTEQUE_EXT_COLOR(5)
#define PASTEQUE_COLOR_YELLOW PASTEQUE_EXT_COLOR(6)
#define PASTEQUE_COLOR_BLUE PASTEQUE_EXT_COLOR(7)
#define PASTEQUE_COLOR_RED PASTEQUE_EXT_COLOR(8)
#define PASTEQUE_COLOR_DARK_GREEN PASTEQUE_EXT_COLOR(9)
#define PASTEQUE_COLOR_DARK_ORANGE PASTEQUE_EXT_COLOR(10)
#define PASTEQUE_COLOR_WHITE PASTEQUE_EXT_COLOR(11)
#define PASTEQUE_COLOR_BLACK PASTEQUE_EXT_COLOR(12)
#define PASTEQUE_COLOR_BLANK PASTEQUE_EXT_COLOR(13)

// Supplementary background colors
#define PASTEQUE_COLOR_YELLOW_HIGHLIGHT_BG PASTEQUE_EXT_COLOR(32)
#define PASTEQUE_COLOR_YELLOW_FOCUS_BG PASTEQUE_EXT_COLOR(33)
#define PASTEQUE_COLOR_RED_BLINK1_BG PASTEQUE_EXT_COLOR(34)
#define PASTEQUE_COLOR_RED_BLINK2_BG PASTEQUE_EXT_COLOR(35)
#define PASTEQUE_COLOR_GREY_25_BG PASTEQUE_EXT_COLOR(36)
#define PASTEQUE_COLOR_LIGHT_BLUE_BG PASTEQUE_EXT_COLOR(37)
#define PASTEQUE_COLOR_TURQUOISE_BG PASTEQUE_EXT_COLOR(38)
#define PASTEQUE_COLOR_BRONZE_BG PASTEQUE_EXT_COLOR(39)
#define PASTEQUE_COLOR_SILVER_BG PASTEQUE_EXT_COLOR(40)
#define PASTEQUE_COLOR_GOLD_BG PASTEQUE_EXT_COLOR(41)
#define PASTEQUE_COLOR_DARK_PURPLE_BG PASTEQUE_EXT_COLOR(42)

// Supplementary specific background/foreground colors
#define PASTEQUE_COLOR_BLUE_ON_WHITE PASTEQUE_EXT_COLOR(50)
#define PASTEQUE_COLOR_WHITE_ON_WHITE PASTEQUE_EXT_COLOR(51)
#define PASTEQUE_COLOR_WHITE_ON_RED PASTEQUE_EXT_COLOR(52)
#define PASTEQUE_COLOR_WHITE_ON_DARK_GREEN PASTEQUE_EXT_COLOR(53)
#define PASTEQUE_COLOR_WHITE_ON_DARK_ORANGE PASTEQUE_EXT_COLOR(54)

// Dynamic colors
#define PASTEQUE_COLOR_WATERMELON_BG_DYN PASTEQUE_EXT_COLOR(64)
#define PASTEQUE_COLOR_WATERMELON_BG_LIGHT_DYN PASTEQUE_EXT_COLOR(65)
#define PASTEQUE_COLOR_WATERMELON_DYN PASTEQUE_EXT_COLOR(66)
#define PASTEQUE_COLOR_WHITE_ON_WATERMELON_DYN PASTEQUE_EXT_COLOR(67)

/**
 * Initializes all the color and color pairs. Must be called in init.
 */
void initColors();

// Updates dynamic colors, which currently are: PASTEQUE_COLOR_WATERMELON_DYN
void colorsUpdateDynamic(unsigned long gameTime);

#endif //PROJET_PASTEQUE_COLORS_H
